### PR TITLE
Fix UART3 Pin swap made to Swan hardware

### PR DESCRIPTION
**Pull request by bsatrom**
We found an issue with UART3 in the Swan hardware and need to swap PB10 and PB11. This small fix propagates that to the variant_SWAN.h file

### CODE REVIEW

**Review by fpistm — COMMENTED** [review]
Don't know why you want change this but this is not correct as this will not match the digital pin array:

https://github.com/bsatrom/Arduino_Core_STM32/blob/c7c4e35b8d81742077f0778e94a0eec394e0c8cf/variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN.cpp#L51-L52

Moreover PB11 is Tx pin: https://github.com/bsatrom/Arduino_Core_STM32/blob/c7c4e35b8d81742077f0778e94a0eec394e0c8cf/variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/PeripheralPins_SWAN.c#L206

and PB10 Rx: 
https://github.com/bsatrom/Arduino_Core_STM32/blob/c7c4e35b8d81742077f0778e94a0eec394e0c8cf/variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/PeripheralPins_SWAN.c#L228

**Comment by jwiedey** [comment]
On our Swan board:
`PB10 == TX3`
`PB11 == RX3`

However, on the prototypes of our Swan Carrier board that breaks out all of the pins, the silkscreen has the pin names reversed.
The existing variant_SWAN.h matches these incorrect prototype Swan Carrier boards

This change will cause the file to match the bare Swan board and the corrected Swan Carrier.

**Comment by fpistm** [comment]
> On our Swan board:
> `PB10 == TX3`
> `PB11 == RX3`
> 
> However, on the prototypes of our Swan Carrier board that breaks out all of the pins, the silkscreen has the pin names reversed.
> The existing variant_SWAN.h matches these incorrect prototype Swan Carrier boards
> 
> This change will cause the file to match the bare Swan board and the corrected Swan Carrier.

Honestly I don't understand your point.
From STM32 point of view: 
- PB10 is LPUART1 RX pin
- PB11 is  LPUART1 Tx pin

Even if you got an silkscreen issue the variant have to define properly the pin definition. PB10 refers to the MCU pin not the silkscreen. If you want to set PB10 to match PB_11 this is really not a good idea.

If you want inverse it in the variant_SWAN.h, this is not a problem but you have to invert it in the variant_SWAN.cpp else this will not match...

**Comment by jwiedey** [comment]
Hello Frederic, 

Blues "RX3/TX3" notation refers to USART3, not LPUART1.

As documented in Table 16 of the [datasheet](https://www.st.com/resource/en/datasheet/stm32l4r5vi.pdf), we use:
- PB10 as USART3_TX (AF7)
- PB11 as USART3_RX (AF7)

We got this mapping correct in the layout and marking of our Swan board, but mistakenly reversed the pins of the Carrier board.
Since the Carrier board and variant_SWAN.* are **both** reversed, the current setup works correctly(!)
But we need to swap the function of these two pins so that our fixed Carrier board will work correctly.
Please help us to make the necessary changes to the .h and .cpp files to reverse these pins.

Thanks,
John

**Comment by fpistm** [comment]
Hi @jwiedey 
OK. My mistake I do not pay attention that PB10/PB11 can also be USART3 with signal inverted.
As in a general way end user prefers LPUART instead of USART.
I will do the missing part.

**Comment by fpistm** [comment]
I've updated your branch like this USART3 is well used else LPUART1 was used. 
Pay attention I amend your commit.

**Review by fpistm — APPROVED** [review]

**Comment by bsatrom** [comment]
thanks @fpistm!

**Pull request merged**
